### ISSUE TITLE
Voice Transformation on Impaired Speech

### ISSUE THREAD

**Issue by Raha304** [b04901014/UUVC#1]
Hi, dear Li-Wei

I am working on dysarthric voice conversion and I want to use your idea in the " Generative Adversarial Networks for Unpaired Voice Transformation on Impaired Speech " paper. 
I saw your repo for this paper but I don't understand which part of the code is related to perceptual similarity implementation.
I am so thankful if you can help me with this problem. 
Pleeeeeeeeeeease

**Comment by b04901014** [comment]
Hi,

Sorry for the late reply. It's been years since I visit this codebase.
If you are referring to the Eq. 4 in the paper, I think it's at https://github.com/b04901014/ISGAN/blob/master/src/model.py#L176
which simply calculates the L1 distance of the discriminator layers between speech segments.

**Comment by b04901014** [comment]
I found the issue in the original repo... I'll close this one.
